const UpdateProductContentData = {
  product1: {
    data: [
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 30,
    comments: 122,
    showCase: 'Y',
  },
  product2: {
    data: [
      { img: 'img2.jpg' },
      { img: 'img2.jpg' },
      { img: 'img2.jpg' },
      { img: 'img2.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 15,
    comments: 133,
    showCase: 'N',
  },
  product3: {
    data: [
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 5,
    comments: 100,
    showCase: 'Y',
  },
};

export default UpdateProductContentData;