const UpdateProductContentData = {
  product1: {
    data: [
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
      { img: 'img1.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 30,
    comments: 122,
    showCase: 'Y',
  },
  product2: {
    data: [
      { img: 'img2.jpg' },
      { img: 'img2.jpg' },
      { img: 'img2.jpg' },
      { img: 'img2.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 15,
    comments: 133,
    showCase: 'N',
  },
  product3: {
    data: [
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
      { img: 'img3.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 0,
    comments: 20,
    showCase: 'N',
  },
  product4: {
    data: [
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
      { img: 'img4.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 15,
    comments: 133,
    showCase: 'N',
  },
  product5: {
    data: [
      { img: 'img5.jpg' },
      { img: 'img5.jpg' },
      { img: 'img5.jpg' },
      { img: 'img5.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 15,
    comments: 133,
    showCase: 'Y',
  },
  product6: {
    data: [
      { img: 'img6.jpg' },
      { img: 'img6.jpg' },
      { img: 'img6.jpg' },
      { img: 'img6.jpg' },
      { img: 'img6.jpg' },
      { img: 'img6.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 0,
    comments: 100,
    showCase: 'Y',
  },
  product7: {
    data: [
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
      { img: 'img7.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 45,
    comments: 200,
    showCase: 'N',
  },
  product8: {
    data: [
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
      { img: 'img8.jpg' },
    ],
    title: '버켄스탁 인기상품 재입고',
    time: 15,
    comments: 133,
    showCase: 'Y',
  },
};

export default UpdateProductContentData;